### ISSUE TITLE
Certain upgrades can't be trained

### ISSUE THREAD

**Issue by 11132113** [tukkek/javelin#20] opened 2016-07-02 09:22 UTC
Some upgrades can't be trained to certain units in some games or after certain upgrades are acquired.

ex game 1:

Train ability (intelligence) cannot be trained to: orc, half-orc, hill dwarf (starting units).
Train ability (intelligence) cannot be trained to: young black dragon, small earth elemental (drafted units).
Train ability (intelligence) CAN be trained to: azer, small earth elemental (drafted units).

The above stay the same in different towns.
Other stats are always available (constitution).

ex game 2:

Train ability (intelligence) CAN be trained to: orc, half-orc, hill dwarf (starting units).
Train ability (intelligence) cannot be trained anymore after these units upgrade aristocrat.

Here's the save for game 1, on the last version at this date:
[javelin.zip](https://github.com/tukkek/javelin/files/344474/javelin.zip)

Change extension to .rar

**Comment by tukkek** [comment] 2016-07-02 13:04
Very cool! Haven't had the time to see to this bug yet but just wanted to let you know that the save file opened properly now that we're on the same version again! Knowing this works should help a lot with testing in the future! Thanks again.

**Comment by tukkek** [comment] 2016-07-02 13:08
By the way I've updated the wiki with information on the game's debug mode. Ideally you should be testing the game on normal mode but maybe you'll think the benefits are worth the trouble of editing you `javelin.bat` file: https://github.com/tukkek/javelin/wiki/Development-options#debug-mode

**Comment by tukkek** [comment] 2016-07-02 13:11
For my own information: the save file provided here is compatible with development version 41296c0f8defb71fa38d4aa77d9f0d6f2b505635.

**Comment by tukkek** [comment] 2016-07-03 23:51
Just so you know: as far as the source code is concerned there are no difference between starting and drafted units. The only units that are "different" are mercenaries (which you can hire on Dwellings, from the Mercenaries Guild or from certain fights if you have high enough Diplomacy).

About the bug: sorry for the delay but this took me a lot more time than I had thought. The thing is that certain upgrades (like class levels and raising Intelligence) would create a deficit in skill points, which would result in a negative score for XP cost. This would result in the upgrading system ignoring these upgrades. This is a very brief explanation, let me know if you want me to go into more the detail.

The solution I found was to actually come closer to the original d20 rules and allow you to select skills at any point you choose to advance in a class level or when you raise intelligence (if that actually results in extra skill points to spend, which doesn't necessarily always happen). I think that is pretty cool though! Before that you had to find the proper Town to raise you skills - and with each passing release skills are becoming more important! I think that is a cool addition to the game and it wouldn't have happened without your feedback, so thanks a lot (once again) :D

This should also solve the problem of the game not letting you reach past a certain level in some classes (for the same reason - since classes are supposed to give you skill points to spend it could result in a negative XP cost because these points were just being discarded before this patch). I haven't reproduced this bug locally though so I can't be sure as of now.

This took me a while because I needed to create a new screen for skill training, and there are a few special rules like maxed skills, class skills, cross-class skills, etc. Not to mention I had to make modifications and check a lot of places where upgrades are used (starting squad selection, towns, adventurers guild, mercenary guild and planar fights). I'm telling you this because I have done my initial testing and everything seems to be running fine but if you want to go ahead and test it some more I'd be a lot more secure about making a big chance like this so late in the release cycle!

With that I think I'm closing all the short-term issues for 1.6. Let me know if I forgot something important or if you come across anything else! Thanks for all the help so far! Here is the download link for the latest update https://github.com/tukkek/javelin/releases/download/1.6b/javelin.zip

**Closed by tukkek** 2016-07-03 23:51 UTC
